### ISSUE TITLE
duvida sobre o exercício. 

### ISSUE THREAD

**Issue by Assisneto** [DiegoPinho/entendendo-es6#2]
Questão 4 do capitulo 4. minha implementação esta correta? 
function criaIterador (lista){
  return lista[Symbol.iterator]();
}
ela ficou bem diferente da implementação do gabarito.

**Comment by DiegoPinho** [comment]
Fala @Assisneto, tudo bem? A ideia no exercício é criar um iterador para o array, como se esta implementação não existisse no javascript. Então por exemplo, ao invés de fazer isso:

``` javascript
var array = [1,2,3,4];
var iterador = array[Symbol.iterator]();
iterador.next(); // { value: 1, done: false }
```

A ideia é criar a função `criaIterador` que será uma implementação do que temos hoje como o `Symbol.Iterator`. O que você precisa fazer é devolver um objeto que tenha a função `next` que toda vez que for executada, irá agir como o Symbol.Iterator. No final ficará algo assim:
``` javascript
var array = [1,2,3,4];
var iterador = criaIterador(array);
iterador.next(); // { value: 1, done: false }
function criaIterador(array) {
    return {
       next: function() {
         // sua implementação
       }
    };
}
```

Espero que tenha ficado claro! Lembrando que o gabarito é apenas uma sugestão de implementação, na programação é possível fazer várias coisas de vários jeitos diferentes ;)

Abraços!

**Comment by Assisneto** [comment]
Muito obrigado por esclarecer minhas duvidas, e aproposito seu livro e muito bom!!!!.

**Comment by DiegoPinho** [comment]
Fico **muito feliz** que tenha gostado! :)
